using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UIElements;

public class Slime : MonoBehaviour
{
    [Header("Movement")]
    private float moveSpeed;
    private float detectionRange;
    
    [Header("Ground Check")]
    public float groundCheckDistance = 0.2f;
    public LayerMask groundLayer;
    public Vector2 groundCheckSize = new Vector2(0.5f, 0.1f);

    [Header("Collision")]
    public CompositeCollider2D compositeCollider;

    [Header("Damage")]
    private float knockbackForce;
    private float damageCooldown;
    private float nextDamageTime;

    public int baseDamage = 10; // ê¸°ë³¸ ê³µê²©ë ¥
    
    public DamageMultiplier damageMultiplier; // ê³µê²©ë ¥ ë¹„ìœ¨ì„ ìœ„í•œ ScriptableObject
    public int attackDamage;

    private Rigidbody2D rb;
    private SpriteRenderer spriteRenderer;
    private Transform playerTransform;
    private bool isGrounded;
    private bool isFacingRight = false;

    [Header("Health")]
    public float baseHealth = 100f; // ê¸°ë³¸ ì²´ë ¥
    public HealthMultiplier healthMultiplier; // ì²´ë ¥ ë¹„ìœ¨ì„ ìœ„í•œ ScriptableObject
    public float calculatedHealth;

    [Header("Item Drop")]
    [SerializeField] private GameObject itemPrefab; // ì•„ì´í…œ í”„ë¦¬íŒ¹
    private InventoryManager inventoryManager;
    [Header("Attack")]
    public int dashForce = 15;
    public int dashCooltime = 3;
    public int dashDemage= 30;
    public float jumpForce = 5f;
    public float jumpHorizontalForce = 3f; // ëŒ€ê°ì„  ì´ë™ì„ ìœ„í•œ ìˆ˜í‰ í˜
    public GameObject SlimeSmashPrefab; // ì›í˜• ê³µê²© ì´í™íŠ¸ í”„ë¦¬íŒ¹
    public GameObject DownAttackPrefab;
    public GameObject FrontAttackPrefab;
    private Transform Pivot;
    [Header("Animation")]
    public Animator anim;
    

    bool isDead;

    void Start()
    {
        isDead=false;
        // GameManagerì—ì„œ ê°’ ê°€ì ¸ì˜¤ê¸°
        moveSpeed = GameManager.Instance.meleeEnemyMoveSpeed;
        detectionRange = GameManager.Instance.meleeEnemyDetectionRange;
        knockbackForce = GameManager.Instance.meleeEnemyKnockbackForce;
        damageCooldown = GameManager.Instance.meleeEnemyDamageCooldown;
        Pivot = transform.Find("pivot");

        rb = GetComponent<Rigidbody2D>();
        spriteRenderer = GetComponent<SpriteRenderer>();
        anim = GetComponent<Animator>();
        playerTransform = GameObject.FindGameObjectWithTag("Player").transform;

        // ì²´ë ¥ê³¼ ê³µê²©ë ¥ ì´ˆê¸°í™”
        float healthMultiplierValue = healthMultiplier.GetHealthMultiplier(GameManager.Instance.Stage, GameManager.Instance.Chapter);
        calculatedHealth = baseHealth * healthMultiplierValue;

        attackDamage = Mathf.RoundToInt(baseDamage * damageMultiplier.GetDamageMultiplier(GameManager.Instance.Stage, GameManager.Instance.Chapter));

        rb.constraints = RigidbodyConstraints2D.FreezeRotation;
        rb.gravityScale = 2.5f;
        rb.collisionDetectionMode = CollisionDetectionMode2D.Continuous;  // ì—°ì† ì¶©ëŒ ê°ì§€ ëª¨ë“œë¡œ ë³€ê²½

        // ê¸°ì¡´ ColliderëŠ” ë¬¼ë¦¬ì  ì¶©ëŒìš©ìœ¼ë¡œ ì‚¬ìš©
        GetComponent<Collider2D>().isTrigger = false;
        

        // ìƒˆë¡œìš´ Trigger Collider ì¶”ê°€
        BoxCollider2D triggerCollider = gameObject.AddComponent<BoxCollider2D>();
        triggerCollider.isTrigger = true;
        // ê¸°ì¡´ Colliderì™€ ê°™ì€ í¬ê¸°ë¡œ ì„¤ì •
        triggerCollider.size = GetComponent<BoxCollider2D>().size;
        triggerCollider.offset = GetComponent<BoxCollider2D>().offset;

        gameObject.layer = LayerMask.NameToLayer("Enemy");

        // ì”¬ì— ìˆëŠ” ëª¨ë“  Enemyë“¤ê³¼ì˜ ì¶©ëŒì„ ë¬´ì‹œ
        RangedEnemy[] rangedEnemies = FindObjectsOfType<RangedEnemy>();
        MeleeEnemy[] meleeEnemies = FindObjectsOfType<MeleeEnemy>();

        foreach (var enemy in meleeEnemies)
        {
            if (enemy != this)  // ìê¸° ìì‹ ì€ ì œì™¸
            {
                Physics2D.IgnoreCollision(GetComponent<Collider2D>(), enemy.GetComponent<Collider2D>(), true);
            }
        }

        foreach (var enemy in rangedEnemies)
        {
            Physics2D.IgnoreCollision(GetComponent<Collider2D>(), enemy.GetComponent<Collider2D>(), true);
        }
        anim.SetInteger("skillNum",9);
        StartCoroutine(StopMovement(4f));
    }

    private void Awake()
    {
        if (InventoryManager.Instance == null)
        {
            Debug.LogError("InventoryManager not found in the scene.");
            return; // InventoryManagerê°€ ì—†ìœ¼ë©´ ë©”ì„œë“œ ì¢…ë£Œ
        }
        canMove = true;

        inventoryManager = InventoryManager.Instance; // inventoryManager ì´ˆê¸°í™”
    }
    Vector2 direction;
    bool canMove;
    private int direc;
    void Update()
    {
        if(!isDead){
        // í”Œë ˆì´ì–´ê°€ ì£½ì—ˆê±°ë‚˜ ì—†ìœ¼ë©´ ë” ì´ìƒ ì§„í–‰í•˜ì§€ ì•ŠìŒ
        if (PlayerController.IsDead || playerTransform == null)
        {
            // ì •ì§€
            rb.velocity = new Vector2(0, rb.velocity.y);
            return;
        }
        direction = (playerTransform.position - Pivot.position).normalized;
        if(direction.x>0){
        direc = 1;
        }
        else{
            direc = -1;
        }
        skillTimer+=Time.deltaTime;
        int skillNum;
        if (skillTimer >= skillInterval) // 1ë¶„ë§ˆë‹¤ í•œë²ˆì”© ëœë¤ìœ¼ë¡œ ìŠ¤í‚¬ ì‹¤í–‰
        {
            skillNum = Random.Range(0,4);// ìŠ¤í‚¬ 4ê°œ
            skillTimer = 0f; // íƒ€ì´ë¨¸ ì´ˆê¸°í™”
            StartCoroutine(mySkill(skillNum));
        }

        // í”Œë ˆì´ì–´ì™€ì˜ ê±°ë¦¬ ì²´í¬
        float distanceToPlayer = Vector2.Distance(transform.position, playerTransform.position);
        // xì¶• ë°©í–¥ìœ¼ë¡œë§Œ ì´ë™
        if(canMove){
            rb.velocity = new Vector2(direc* moveSpeed, rb.velocity.y);
        }
        else{
            rb.velocity =new Vector2(0, rb.velocity.y);
        }
            // ìŠ¤í”„ë¼ì´íŠ¸ ë°©í–¥ ì „í™˜
            if (direction.x < 0 && !isFacingRight)
            {
                Flip();
            }
            else if (direction.x > 0 && isFacingRight)
            {
                Flip();
            }
        if(isDashing){
            rb.velocity = new Vector2(direc * dashForce, rb.velocity.y);
        }
        // ì²´ë ¥ ì²´í¬
        if (calculatedHealth <= 0)
        {
            Death();
        }
        //í…ŒìŠ¤íŠ¸ìš©
        // ë””ë²„ê·¸ìš©: K í‚¤ë¥¼ ëˆ„ë¥´ë©´ ëª¬ìŠ¤í„° ì²´ë ¥ì„ 0ìœ¼ë¡œ ì„¤ì •
        if (Input.GetKeyDown(KeyCode.K))
        {
            Debug.Log("Debug: Monster health set to 0 manually.");
            calculatedHealth = 0;
            Death();
        }
        }
    }
    void Flip()
    {
        isFacingRight = !isFacingRight;
        //spriteRenderer.flipX = !spriteRenderer.flipX;
        Vector3 scale = transform.localScale;
        scale.x *= -1;
        transform.localScale = scale;
        transform.position = transform.position + new Vector3(3*direc,0,0);
    }
    
    private void myFlip(){
        
    }
    private float skillTimer = 0f;
    public float skillInterval = 3f;
    public int custumSkillnum=0;
   IEnumerator mySkill(int skillNum){
        
        if (custumSkillnum==7){
            skillNum = Random.Range(0,5);
        }
        else{
            skillNum=custumSkillnum;
        }
        
        //ìºìŠ¤íŒ… ì‹œê°„
        
        Debug.Log("ìŠ¤í‚¬ ìºìŠ¤íŒ… ì‹œì‘ 1ì´ˆë’¤ ìŠ¤í‚¬ì‚¬ìš©");
        yield return new WaitForSeconds(1f);
        anim.SetInteger("skillNum",skillNum);
        switch (skillNum)
        {
        case 0:
            StartCoroutine(StopMovement(1f));
            Dash();
            break;
        case 1:
            //SmashAttack();
            break;
        case 2:
            //DownAttack();
            break;
        case 3:
            //FrontAttack();
            break;
        case 4:
            Jump();
            break;
        default:
            Debug.Log("ì˜ëª»ëœ ìŠ¤í‚¬ ë²ˆí˜¸");
            break;
        }
        Debug.Log("ìŠ¤í‚¬"+skillNum+ "ì‹¤í–‰");
    }
    public void ResetToIdle() // ì• ë‹ˆë©”ì´ì…˜ ì´ë²¤íŠ¸ì—ì„œ í˜¸ì¶œë  í•¨ìˆ˜
    {
        anim.SetInteger("skillNum", 9); // Idle ìƒíƒœë¡œ ë³€ê²½
    }
private void Jump(){
    
    Vector2 jumpVector = new Vector2(jumpHorizontalForce *direc , jumpForce);
    rb.velocity = new Vector2(rb.velocity.x, 0); // ê¸°ì¡´ Yì¶• ì†ë„ë¥¼ ì´ˆê¸°í™”
    rb.AddForce(jumpVector, ForceMode2D.Impulse); // í˜ì„ ìˆœê°„ì ìœ¼ë¡œ ê°€í•¨
}
private void FrontAttack(){
    //StopMovement(0.5f);
    // ì´í™íŠ¸ ìƒì„±
    if (FrontAttackPrefab != null)
    {
        GameObject effect = Instantiate(FrontAttackPrefab, Pivot.position+new Vector3(2*direc,0.3f,0), Quaternion.identity);
        effect.transform.SetParent(transform);
        //StartCoroutine(DashCoroutine(0.1f)); //ì•ìœ¼ë¡œ ì´ë™í•˜ë©° ê³µê²©
        
        Destroy(effect, 0.6f); // 0.5ì´ˆ í›„ ì´í™íŠ¸ ì œê±°
        Debug.Log("ì´í™íŠ¸ ì¶œë ¥");
    }
    Debug.Log("íœ˜ë‘ë¥´ê¸° ì‚¬ìš©");
    //anim.SetInteger("skillNum",9);
}

private void SmashAttack()
{
    StartCoroutine(StopMovement(0.5f));
    // ì´í™íŠ¸ ìƒì„±
    
    if (SlimeSmashPrefab != null)
    {
        GameObject effect = Instantiate(SlimeSmashPrefab, Pivot.position+new Vector3(direc*1,0,0), Quaternion.identity);
        effect.transform.SetParent(transform);
        Destroy(effect, 0.4f); // 0.5ì´ˆ í›„ ì´í™íŠ¸ ì œê±°
        Debug.Log("ì´í™íŠ¸ ì¶œë ¥");
    }
    //anim.SetInteger("skillNum",9);
    Debug.Log("ì£¼ìœ„ê³µê²© ê³µê²© ì‚¬ìš©");
}


private void DownAttack()
{
    StartCoroutine(StopMovement(1.0f)); // ëª¬ìŠ¤í„° ë©ˆì¶”ê¸°

    // ë°©í–¥ ë²¡í„° ì •ê·œí™”
    Vector2 shootDirection = direction.normalized;

    // ì´í™íŠ¸ ìƒì„± (í”Œë ˆì´ì–´ ë°©í–¥ìœ¼ë¡œ)
    if (DownAttackPrefab != null)
    {

        // ë ˆì´ì € ì´í™íŠ¸ ìƒì„±
        GameObject effect = Instantiate(DownAttackPrefab, Pivot.position+new Vector3(3*direc,-0.7f,0), Quaternion.identity);
        
        // ì´í™íŠ¸ ì´ë™ (ì†ë„ ì¡°ì ˆ ê°€ëŠ¥)
        Rigidbody2D effectRb = effect.GetComponent<Rigidbody2D>();
        if (effectRb != null)
        {
            effectRb.velocity = shootDirection * 5f; // ì†ë„ ì¡°ì ˆ
        }

        Destroy(effect, 0.7f); // 1.0ì´ˆ í›„ ì´í™íŠ¸ ì œê±°
    }

    Debug.Log("ìŠ¬ë¼ì„ ì•„ë˜ê³µê²© ì‚¬ìš©");
}

private IEnumerator StopMovement(float stopDuration)
    {
        canMove =false;
        Debug.Log("ë³´ìŠ¤ëª¬ìŠ¤í„° ì •ì§€");
        yield return new WaitForSeconds(stopDuration);
        canMove =true; // ì›ë˜ ì†ë„ë¡œ ë³µê·€
    }

    private bool canDash = true;
    private float dashCooldownTimer = 0f;
    private bool isDashing = false;
    private void Dash(){
        
        float dashDirection = direction.x>=0 ? 1f : -1f;
        // í˜„ì¬ ì†ë„ë¥¼ ì´ˆê¸°í™”í•˜ê³  ëŒ€ì‹œ ë°©í–¥ìœ¼ë¡œ í˜ì„ ê°€í•¨
        // ëŒ€ì‹œ ì†ë„ ì„¤ì •
        // ëŒ€ì‹œ ì†ë„ ì§ì ‘ ì„¤ì •
        // ëŒ€ì‹œ ì½”ë£¨í‹´ ì‹œì‘
        StartCoroutine(DashCoroutine(0.5f));
        // ì¿¨ë‹¤ìš´ ì‹œì‘
        canDash = false;
        Debug.Log($"ë³´ìŠ¤ëª¬ìŠ¤í„° ëŒ€ì‰¬ì‚¬ìš©");
    }

    private IEnumerator DashCoroutine(float dashTime)
    {
        isDashing = true;
        int tmp = baseDamage;
        baseDamage = dashDemage;
        canDash = false;
        // ëŒ€ì‹œ ì§€ì† ì‹œê°„
        yield return new WaitForSeconds(dashTime);
        baseDamage = tmp;
        anim.SetInteger("skillNum",9);
        isDashing = false;
    }

    //í…ŒìŠ¤íŠ¸ìš© 
    // ì²´ë ¥ 0ì´ ë˜ë©´ ì•„ì´í…œ ë“œë¡­ ë° ëª¬ìŠ¤í„° íŒŒê´´ ì²˜ë¦¬

    public void OnDeathAnimationEnd()
    {
        Debug.Log("ğŸ’€ ë³´ìŠ¤ ì£½ìŒ ì• ë‹ˆë©”ì´ì…˜ ì¢…ë£Œ - ê²Œì„ì˜¤ë²„ ì²˜ë¦¬ ì‹œì‘");
        GameManager.Instance.ShowGameOver();
        StartCoroutine(DelayLoadScoreBoard());
    }

    private IEnumerator DelayLoadScoreBoard()
    {
        yield return new WaitForSeconds(1.0f); // ğŸ”¥ ì €ì¥í•  ì‹œê°„ í™•ë³´
        SceneManager.LoadScene("ScoreBoard");
    }

    private void Death()
    {
        isDead=true;
        attackDamage=0;
        if (calculatedHealth <= 0)
        {
            //DropItem();
            //Destroy(gameObject);
            Debug.Log("ë³´ìŠ¤ëª¬ìŠ¤í„° ì£½ìŒ");
            anim.SetTrigger("death");
            //MapManager.Instance.SpawnPortal();
        }
    }





    void DropItem()
    {
        if (inventoryManager == null)
        {
            Debug.LogError("InventoryManager is not initialized.");
            return; // inventoryManagerê°€ nullì´ë©´ ë©”ì„œë“œ ì¢…ë£Œ
        }

        if (itemPrefab == null)
        {
            Debug.LogError("Item prefab is not assigned.");
            return; // itemPrefabì´ nullì´ë©´ ï¿½ì„œë“œ ì¢…ë£Œ
        }

        string itemName = inventoryManager.GetItemNameById(0);
        
        // ëœë¤ ID ìƒì„± (0~4 ì¤‘ í•˜ë‚˜)
        int randomId = Random.Range(0, 5);

        // ë“œë ìœ„ì¹˜
        Vector3 dropPosition = transform.position;

        // ì•„ì´í…œ ìƒì„±
        GameObject droppedItem = Instantiate(itemPrefab, dropPosition, Quaternion.identity);

        // ì•„ì´í…œ ì´ˆê¸°í™”
        DroppedItem itemComponent = droppedItem.GetComponent<DroppedItem>();
        if (itemComponent != null)
        {
            itemName = inventoryManager.GetItemNameById(randomId); // IDì— ë”°ë¥¸ ì´ë¦„
            itemComponent.Initialize(randomId, itemName);
        }
        else
        {
            Debug.LogError("DroppedItem component not found on the instantiated item.");
        }

        Debug.Log($"Dropped {itemName} at {dropPosition}");
    }

    // ë””ë²„ê·¸ìš© ì‹œê°í™”
    void OnDrawGizmosSelected()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(transform.position, detectionRange);
    }

    // ìƒˆë¡œ ìŠ¤í°ë˜ëŠ” Enemyë“¤ê³¼ë„ ì¶©ëŒì„ ë¬´ì‹œí•˜ê¸° ìœ„í•œ íŠ¸ë¦¬ê±° ì²´í¬
    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Enemy")||other.CompareTag("Half Tile")||other.CompareTag("Trap Tile"))
        {
            Physics2D.IgnoreCollision(GetComponent<Collider2D>(), other, true);
        }
    }

    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Enemy")||collision.gameObject.CompareTag("Half Tile")||collision.gameObject.CompareTag("Trap Tile"))
        {
            Debug.Log("ë°˜ë¸”ëŸ­ì— ë¶€ë”ªì¹¨");
            Collider2D myCollider = GetComponent<Collider2D>();
            Collider2D otherCollider = collision.collider; // ì¶©ëŒí•œ ì½œë¼ì´ë”
            if (myCollider != null && otherCollider != null)
            {
                Physics2D.IgnoreCollision(myCollider, otherCollider, true);
            }
            return;
        }
        if (collision.gameObject.CompareTag("Player"))
        {
            if (Time.time >= nextDamageTime)
            {
                IDamageable damageable = collision.gameObject.GetComponent<IDamageable>();
                if (damageable != null)
                {
                    Vector2 knockbackDir = (collision.transform.position - transform.position).normalized;
                    knockbackDir.y = 0.5f;
                    
                    damageable.TakeDamage(attackDamage, knockbackDir, knockbackForce);
                    nextDamageTime = Time.time + damageCooldown;
                }
            }
        }
    }
}
